pipeline {
agent any

environment {
IMAGE = "ghcr.io/milo1409/devsecops-lab/devsecops-demo"
TAG = "${BUILD_NUMBER}"
}

stages {

stage('Checkout') {
  steps {
    checkout scm
  }
}

stage('Build Docker Image') {
  steps {
    sh '''
    docker build -t $IMAGE:$TAG .
    docker tag $IMAGE:$TAG $IMAGE:latest
    '''
  }
}

stage('Push Image to GHCR') {
  steps {
    withCredentials([usernamePassword(
      credentialsId: 'ghcr-creds',
      usernameVariable: 'USER',
      passwordVariable: 'TOKEN'
    )]) {
      sh '''
      echo $TOKEN | docker login ghcr.io -u $USER --password-stdin
      docker push $IMAGE:$TAG
      docker push $IMAGE:latest
      '''
    }
  }
}

stage('Deploy to Kubernetes') {
  steps {
    sh '''
    /tmp/kubectl -n devsecops set image deployment/django-demo django-demo=$IMAGE:latest
    /tmp/kubectl -n devsecops rollout status deployment django-demo
    '''
  }
}

}
}
