pipeline {
  agent any

  environment {
    IMAGE = "ghcr.io/milo1409/devsecops-lab/devsecops-demo"
  }

  stages {
    stage('Checkout') {
      steps { checkout scm }
    }

    stage('Install kubectl') {
      steps {
        sh '''
          curl -L -o /tmp/kubectl https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x /tmp/kubectl
          /tmp/kubectl version --client
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
          /tmp/kubectl -n devsecops apply -f k8s/service.yaml
          /tmp/kubectl -n devsecops apply -f k8s/deployment.yaml
          /tmp/kubectl -n monitoring apply -f k8s/servicemonitor.yaml

          # Fuerza a Kubernetes a bajar la imagen nueva de GHCR
          /tmp/kubectl -n devsecops rollout restart deployment/django-demo
          /tmp/kubectl -n devsecops rollout status deployment/django-demo --timeout=180s
        '''
      }
    }
  }
}
