pipeline {
  agent any

  environment {
    KUBECTL = "/tmp/kubectl"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Install kubectl') {
      steps {
        sh '''
          curl -L -o /tmp/kubectl https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
          chmod +x /tmp/kubectl
          /tmp/kubectl version --client
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
          ${KUBECTL} -n devsecops apply -f k8s/service.yaml
          ${KUBECTL} -n devsecops apply -f k8s/deployment.yaml
          ${KUBECTL} -n monitoring apply -f k8s/servicemonitor.yaml
          ${KUBECTL} -n devsecops rollout restart deploy django-demo
          ${KUBECTL} -n devsecops rollout status deploy django-demo --timeout=120s
        '''
      }
    }

  }
}
